"""
Generate a template Excel workbook with correct headers and one sample row per sheet.
No MongoDB connection needed.
"""

import pandas as pd
from openpyxl.styles import PatternFill, Font, Alignment
from openpyxl.utils import get_column_letter

OUTPUT = "/Users/izzet/Desktop/broker_app_template.xlsx"

SHEETS = {
    "trades": {
        "columns": [
            "id", "pirContractNumber", "referenceNumber", "contractNumber", "sellerContractNumber",
            "status", "contractDate", "cropYear",
            "sellerName", "sellerCode", "buyerName", "buyerCode",
            "brokerName", "brokerCode", "coBrokerName", "coBrokerCode",
            "commodityName", "commodityDisplayName", "originName",
            "quantity", "tolerance", "blQuantity",
            "pricePerMT", "currency", "brokeragePerMT", "brokerageAccount", "totalCommission",
            "deliveryTerm", "incoterms", "paymentTerms",
            "loadingPortName", "dischargePortName", "basePortName",
            "shipmentWindowStart", "shipmentWindowEnd", "vesselName",
            "buyerPaymentDate", "invoiceDate", "invoiceNo", "invoicePaid",
            "diReceived", "specialConditions", "notes",
            "createdAt", "updatedAt",
        ],
        "sample": {
            "id": "abc123", "pirContractNumber": "PIR-25-AB1234", "referenceNumber": "PIR-25-AB1234",
            "contractNumber": "PIR-25-AB1234", "sellerContractNumber": "N/A",
            "status": "confirmation", "contractDate": "01/05/2025", "cropYear": "2025",
            "sellerName": "Acme Grain Ltd", "sellerCode": "ACM",
            "buyerName": "Delta Foods", "buyerCode": "DEL",
            "brokerName": "PIR Grain", "brokerCode": "PIR",
            "coBrokerName": "", "coBrokerCode": "",
            "commodityName": "Wheat", "commodityDisplayName": "Russian Wheat, Crop 2025", "originName": "Russia",
            "quantity": 25000, "tolerance": "5 PWWD MOLOO", "blQuantity": "",
            "pricePerMT": 215.0, "currency": "USD", "brokeragePerMT": 0.5,
            "brokerageAccount": "seller", "totalCommission": 12500.0,
            "deliveryTerm": "CFR", "incoterms": "CFR", "paymentTerms": "100% LC at sight",
            "loadingPortName": "Novorossiysk", "dischargePortName": "Mersin", "basePortName": "Novorossiysk",
            "shipmentWindowStart": "01/06/2025", "shipmentWindowEnd": "30/06/2025", "vesselName": "MV EXAMPLE",
            "buyerPaymentDate": "", "invoiceDate": "", "invoiceNo": "", "invoicePaid": False,
            "diReceived": False, "specialConditions": "", "notes": "",
            "createdAt": "2025-05-01T08:00:00+00:00", "updatedAt": "2025-05-01T08:00:00+00:00",
        }
    },
    "partners": {
        "columns": [
            "id", "companyName", "companyCode", "contactPerson",
            "address", "city", "country", "email", "phone", "whatsapp",
            "type", "origins", "taxIdNo", "taxOffice", "notes",
            "createdAt", "updatedAt",
        ],
        "sample": {
            "id": "abc124", "companyName": "Acme Grain Ltd", "companyCode": "ACM",
            "contactPerson": "John Smith", "address": "123 Trade St",
            "city": "Moscow", "country": "Russia", "email": "john@acme.com",
            "phone": "+7 999 000 0000", "whatsapp": "+7 999 000 0000",
            "type": '["seller"]', "origins": '["Russia"]',
            "taxIdNo": "1234567890", "taxOffice": "Moscow Tax Office", "notes": "",
            "createdAt": "2025-01-01T08:00:00+00:00", "updatedAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "invoices": {
        "columns": [
            "id", "invoiceNumber", "vendorName", "vendorCode",
            "amount", "currency", "invoiceDate", "dueDate", "paymentDate",
            "category", "description", "status", "direction",
            "tradeId", "autoGenerated", "createdAt",
        ],
        "sample": {
            "id": "abc125", "invoiceNumber": "COMM-PIR-25-AB1234", "vendorName": "Acme Grain Ltd",
            "vendorCode": "ACM", "amount": 12500.0, "currency": "USD",
            "invoiceDate": "15/06/2025", "dueDate": "30/06/2025", "paymentDate": "",
            "category": "Commission Payment", "description": "Brokerage commission for Wheat trade",
            "status": "pending", "direction": "incoming",
            "tradeId": "abc123", "autoGenerated": True,
            "createdAt": "2025-06-15T08:00:00+00:00",
        }
    },
    "vessels": {
        "columns": ["id", "name", "imoNumber", "flag", "builtYear", "vesselType", "createdAt"],
        "sample": {
            "id": "abc126", "name": "MV EXAMPLE", "imoNumber": "9876543",
            "flag": "Malta", "builtYear": 2010, "vesselType": "Bulk Carrier",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "commodities": {
        "columns": ["id", "name", "code", "group", "hsCode", "description", "specs", "createdAt"],
        "sample": {
            "id": "abc127", "name": "Wheat", "code": "WHT", "group": "Grains",
            "hsCode": "1001.99", "description": "Feed/Milling Wheat",
            "specs": "Protein min 12.5%, Moisture max 13.5%",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "origins": {
        "columns": ["id", "name", "adjective", "code", "createdAt"],
        "sample": {
            "id": "abc128", "name": "Russia", "adjective": "Russian", "code": "RU",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "ports": {
        "columns": ["id", "name", "type", "country", "countryCode", "createdAt"],
        "sample": {
            "id": "abc129", "name": "Novorossiysk", "type": "loading",
            "country": "Russia", "countryCode": "RU",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "surveyors": {
        "columns": ["id", "name", "contact", "countriesServed", "createdAt"],
        "sample": {
            "id": "abc130", "name": "SGS Turkey", "contact": "sgs@example.com",
            "countriesServed": '["Turkey", "Russia"]',
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "events": {
        "columns": [
            "id", "title", "date", "dateTo", "type",
            "description", "tradeId", "partnerId", "paymentDueDate", "createdAt",
        ],
        "sample": {
            "id": "abc131", "title": "Commission Due", "date": "30/06/2025", "dateTo": "",
            "type": "payment", "description": "Commission due for PIR-25-AB1234",
            "tradeId": "abc123", "partnerId": "", "paymentDueDate": "30/06/2025",
            "createdAt": "2025-05-01T08:00:00+00:00",
        }
    },
    "bank_accounts": {
        "columns": ["id", "bankName", "accountName", "iban", "swift", "currency", "country", "createdAt"],
        "sample": {
            "id": "abc132", "bankName": "Garanti BBVA", "accountName": "PIR Grain Pulses",
            "iban": "TR000000000000000000000000", "swift": "TGBATRIS",
            "currency": "USD", "country": "Turkey",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "vendors": {
        "columns": ["id", "name", "contact", "email", "phone", "category", "notes", "createdAt"],
        "sample": {
            "id": "abc133", "name": "Example Vendor", "contact": "Jane Doe",
            "email": "jane@vendor.com", "phone": "+90 555 000 0000",
            "category": "other", "notes": "",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "users": {
        "columns": ["id", "name", "username", "email", "whatsapp", "mobile", "role", "createdAt"],
        "sample": {
            "id": "abc134", "name": "Admin User", "username": "admin",
            "email": "admin@example.com", "whatsapp": "+90 555 000 0001",
            "mobile": "+90 555 000 0001", "role": "admin",
            "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "disport_agents": {
        "columns": ["id", "name", "port", "contact", "email", "tel", "whatsapp", "address", "createdAt"],
        "sample": {
            "id": "abc135", "name": "Mersin Port Agency", "port": "Mersin",
            "contact": "Ali Yılmaz", "email": "ali@mersinagency.com",
            "tel": "+90 324 000 0000", "whatsapp": "+90 532 000 0000",
            "address": "Mersin, Turkey", "createdAt": "2025-01-01T08:00:00+00:00",
        }
    },
    "bank_statements": {
        "columns": ["id", "month", "year", "description", "fileName", "createdAt"],
        "sample": {
            "id": "abc136", "month": 5, "year": 2025,
            "description": "May 2025 USD Account", "fileName": "statement_may2025.pdf",
            "createdAt": "2025-06-01T08:00:00+00:00",
        }
    },
}


def style_header_row(ws, n_cols):
    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    header_font = Font(color="FFFFFF", bold=True, size=10)
    for col in range(1, n_cols + 1):
        cell = ws.cell(row=1, column=col)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=False)


def style_sample_row(ws, n_cols):
    sample_fill = PatternFill(start_color="D9E1F2", end_color="D9E1F2", fill_type="solid")
    for col in range(1, n_cols + 1):
        ws.cell(row=2, column=col).fill = sample_fill


def main():
    with pd.ExcelWriter(OUTPUT, engine="openpyxl") as writer:
        for sheet_name, info in SHEETS.items():
            cols = info["columns"]
            sample = info["sample"]
            sample_row = {c: sample.get(c, "") for c in cols}
            df = pd.DataFrame([sample_row], columns=cols)
            df.to_excel(writer, sheet_name=sheet_name[:31], index=False)

            ws = writer.sheets[sheet_name[:31]]
            style_header_row(ws, len(cols))
            style_sample_row(ws, len(cols))
            ws.row_dimensions[1].height = 20

            for col_idx, col_name in enumerate(cols, 1):
                val_len = len(str(sample_row.get(col_name, "")))
                width = min(max(len(col_name), val_len) + 3, 50)
                ws.column_dimensions[get_column_letter(col_idx)].width = width

    print(f"Template saved to: {OUTPUT}")


if __name__ == "__main__":
    main()
