import os

from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from fastapi.responses import FileResponse

from database import (q_all, q_one, insert_document, update_document, delete_document,
                      serialize_doc_row, create_notification)
from auth import require_roles
from models import InvoiceCreate, BankStatementCreate

UPLOAD_DIR = os.environ.get("UPLOAD_DIR", "/app/backend/uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

accounting_access = require_roles("admin", "accountant")

router = APIRouter(prefix="/api", tags=["accounting"])


# ─── Invoices ────────────────────────────────────────────────
@router.get("/invoices")
def list_invoices(user=Depends(accounting_access)):
    return [serialize_doc_row(i) for i in q_all("SELECT * FROM invoices ORDER BY created_at DESC")]


@router.post("/invoices")
def create_invoice(invoice: InvoiceCreate, user=Depends(accounting_access)):
    row = insert_document("invoices", invoice.dict())
    create_notification("accounting", f"New invoice: {invoice.invoiceNumber}", str(row["id"]), user.get("username"))
    return serialize_doc_row(row)


@router.put("/invoices/{invoice_id}")
def update_invoice(invoice_id: str, invoice: InvoiceCreate, user=Depends(accounting_access)):
    row = update_document("invoices", invoice_id, set_fields=invoice.dict())
    create_notification("accounting", f"Invoice updated: {invoice.invoiceNumber}", invoice_id, user.get("username"))
    return serialize_doc_row(row)


@router.delete("/invoices/{invoice_id}")
def delete_invoice(invoice_id: str, user=Depends(accounting_access)):
    existing = q_one("SELECT data FROM invoices WHERE id = %s", (invoice_id,))
    num = (existing.get("data") or {}).get("invoiceNumber", "") if existing else invoice_id
    delete_document("invoices", invoice_id)
    create_notification("accounting", f"Invoice deleted: {num}", invoice_id, user.get("username"))
    return {"message": "Deleted"}


@router.patch("/invoices/{invoice_id}/payment-date")
def update_invoice_payment_date(invoice_id: str, body: dict, user=Depends(accounting_access)):
    payment_date = body.get("paymentDate", "")
    inv = q_one("SELECT * FROM invoices WHERE id = %s", (invoice_id,))
    if not inv:
        return {"error": "Invoice not found"}
    status = "paid" if payment_date else "pending"
    update_document("invoices", invoice_id, set_fields={"paymentDate": payment_date, "status": status})
    inv_data = inv.get("data") or {}
    trade_id = inv_data.get("tradeId")
    if trade_id and inv_data.get("autoGenerated"):
        update_document("trades", trade_id, set_fields={
            "buyerPaymentDate": payment_date, "invoicePaid": bool(payment_date)})
    return serialize_doc_row(q_one("SELECT * FROM invoices WHERE id = %s", (invoice_id,)))


@router.post("/invoices/{invoice_id}/upload-file")
async def upload_invoice_file(invoice_id: str, file: UploadFile = File(...), user=Depends(accounting_access)):
    if not q_one("SELECT 1 FROM invoices WHERE id = %s", (invoice_id,)):
        raise HTTPException(status_code=404, detail="Invoice not found")
    inv_dir = os.path.join(UPLOAD_DIR, "invoices")
    os.makedirs(inv_dir, exist_ok=True)
    ext = os.path.splitext(file.filename)[1]
    path = os.path.join(inv_dir, f"{invoice_id}{ext}")
    with open(path, "wb") as f:
        f.write(await file.read())
    update_document("invoices", invoice_id, set_fields={"invoiceFileName": file.filename, "invoiceFilePath": path})
    return serialize_doc_row(q_one("SELECT * FROM invoices WHERE id = %s", (invoice_id,)))


@router.get("/invoices/{invoice_id}/download-file")
def download_invoice_file(invoice_id: str, user=Depends(accounting_access)):
    inv = q_one("SELECT data FROM invoices WHERE id = %s", (invoice_id,))
    data = (inv.get("data") or {}) if inv else {}
    if not data.get("invoiceFilePath") or not os.path.exists(data["invoiceFilePath"]):
        raise HTTPException(status_code=404, detail="No file found")
    return FileResponse(data["invoiceFilePath"], filename=data.get("invoiceFileName", "invoice.pdf"),
                        media_type="application/octet-stream")


@router.delete("/invoices/{invoice_id}/upload-file")
def delete_invoice_file(invoice_id: str, user=Depends(accounting_access)):
    inv = q_one("SELECT data FROM invoices WHERE id = %s", (invoice_id,))
    if not inv:
        raise HTTPException(status_code=404, detail="Invoice not found")
    path = (inv.get("data") or {}).get("invoiceFilePath")
    if path and os.path.exists(path):
        os.remove(path)
    update_document("invoices", invoice_id, set_fields={}, unset_fields=["invoiceFileName", "invoiceFilePath"])
    return serialize_doc_row(q_one("SELECT * FROM invoices WHERE id = %s", (invoice_id,)))


# ─── Bank Statements ────────────────────────────────────────
@router.get("/bank-statements")
def list_bank_statements(user=Depends(accounting_access)):
    return [serialize_doc_row(s) for s in q_all("SELECT * FROM bank_statements ORDER BY created_at DESC")]


@router.post("/bank-statements")
def create_bank_statement(stmt: BankStatementCreate, user=Depends(accounting_access)):
    row = insert_document("bank_statements", stmt.dict())
    create_notification("accounting", "New bank statement added", str(row["id"]), user.get("username"))
    return serialize_doc_row(row)


@router.post("/bank-statements/upload")
async def upload_bank_statement(file: UploadFile = File(...), month: int = Form(...), year: int = Form(...),
                                description: str = Form(""), bankAccountId: str = Form(""),
                                user=Depends(accounting_access)):
    allowed = ('.pdf', '.doc', '.docx', '.xls', '.xlsx', '.csv', '.jpg', '.jpeg', '.png')
    if not file.filename.lower().endswith(allowed):
        raise HTTPException(status_code=400, detail="File type not allowed")
    row = insert_document("bank_statements", {
        "month": month, "year": year, "description": description, "bankAccountId": bankAccountId,
        "fileName": file.filename})
    stmt_id = str(row["id"])
    ext = file.filename.rsplit('.', 1)[-1] if '.' in file.filename else 'pdf'
    stored_name = f"stmt_{stmt_id}.{ext}"
    with open(os.path.join(UPLOAD_DIR, stored_name), "wb") as f:
        f.write(await file.read())
    update_document("bank_statements", stmt_id, set_fields={"storedFileName": stored_name})
    create_notification("accounting", "Bank statement uploaded", stmt_id, user.get("username"))
    return serialize_doc_row(q_one("SELECT * FROM bank_statements WHERE id = %s", (stmt_id,)))


@router.put("/bank-statements/{stmt_id}")
def update_bank_statement(stmt_id: str, data: dict, user=Depends(accounting_access)):
    return serialize_doc_row(update_document("bank_statements", stmt_id, set_fields=data))


@router.put("/bank-statements/{stmt_id}/upload")
async def update_bank_statement_upload(stmt_id: str, file: UploadFile = File(...), month: int = Form(...),
                                       year: int = Form(...), description: str = Form(""),
                                       bankAccountId: str = Form(""), user=Depends(accounting_access)):
    ext = file.filename.rsplit('.', 1)[-1] if '.' in file.filename else 'pdf'
    stored_name = f"stmt_{stmt_id}.{ext}"
    with open(os.path.join(UPLOAD_DIR, stored_name), "wb") as f:
        f.write(await file.read())
    update_document("bank_statements", stmt_id, set_fields={
        "month": month, "year": year, "description": description, "bankAccountId": bankAccountId,
        "fileName": file.filename, "storedFileName": stored_name})
    return serialize_doc_row(q_one("SELECT * FROM bank_statements WHERE id = %s", (stmt_id,)))


@router.get("/bank-statements/{stmt_id}/download")
def download_bank_statement(stmt_id: str, user=Depends(accounting_access)):
    stmt = q_one("SELECT data FROM bank_statements WHERE id = %s", (stmt_id,))
    data = (stmt.get("data") or {}) if stmt else {}
    if not data.get("storedFileName"):
        raise HTTPException(status_code=404, detail="No file found")
    filepath = os.path.join(UPLOAD_DIR, data["storedFileName"])
    if not os.path.exists(filepath):
        raise HTTPException(status_code=404, detail="File not found on disk")
    return FileResponse(filepath, filename=data.get("fileName", "bank_statement"), media_type="application/octet-stream")


@router.delete("/bank-statements/{stmt_id}")
def delete_bank_statement(stmt_id: str, user=Depends(accounting_access)):
    delete_document("bank_statements", stmt_id)
    create_notification("accounting", "Bank statement deleted", stmt_id, user.get("username"))
    return {"message": "Deleted"}
